accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'), # User [C]reate
    path('login/', views.login, name='login'), # Session [C]reate
    path('logout/', views.logout, name='logout'), # Session [D]elete
    path('delete/', views.delete, name='delete'), # User [D]elete
    path('edit/', views.edit, name='edit'), # User [U]pdate
    path('password/', views.password, name='password'), # (Password) [U]pdate
]

formclass/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', lambda r: redirect('articles:index'), name='root')
]

# views.py
# def index(request):
#     return redirect('articles:index')

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav>

        {% if user.is_authenticated %}
        <span>{{ user.username }}</span>
        <a href="{% url 'accounts:edit' %}">회원정보수정</a>
        <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="로그아웃">
        </form>
        <form action="{% url 'accounts:delete' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="회원탈퇴">
        </form>
        {% else %}
        <a href="{% url 'accounts:login' %}">로그인</a>
        <a href="{% url 'accounts:signup' %}">회원가입</a>
        {% endif %}
        
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>